using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TurboXml.Serialization.Generator;

[Generator]
public sealed class TurboXmlSerializerGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor ContextMustBePartial = new(
        "TXS001",
        "TurboXml serializer context must be partial",
        "The serializer context '{0}' must be declared partial",
        "TurboXml.Serialization",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor UnsupportedProperty = new(
        "TXS002",
        "Unsupported TurboXml serialization property",
        "Property '{0}' on '{1}' is unsupported: {2}",
        "TurboXml.Serialization",
        DiagnosticSeverity.Error,
        true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contexts = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (generatorContext, _) => GetContext(generatorContext))
            .Where(static candidate => candidate is not null)
            .Collect();

        context.RegisterSourceOutput(contexts, static (productionContext, candidates) =>
        {
            foreach (var candidate in candidates)
            {
                if (candidate is not null)
                {
                    GenerateContext(productionContext, candidate);
                }
            }
        });
    }

    private static ContextCandidate? GetContext(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        var serializableAttributes = symbol.GetAttributes()
            .Where(static attribute => attribute.AttributeClass?.ToDisplayString() == "TurboXml.Serialization.TurboXmlSerializableAttribute")
            .ToImmutableArray();
        if (serializableAttributes.IsDefaultOrEmpty)
        {
            return null;
        }

        return new ContextCandidate(symbol, declaration.Modifiers.Any(SyntaxKind.PartialKeyword), serializableAttributes);
    }

    private static void GenerateContext(SourceProductionContext context, ContextCandidate candidate)
    {
        if (!candidate.IsPartial)
        {
            context.ReportDiagnostic(Diagnostic.Create(ContextMustBePartial, candidate.Symbol.Locations.FirstOrDefault(), candidate.Symbol.Name));
            return;
        }

        var skipElements = GetSkipElements(candidate.Symbol);
        var models = new List<ModelInfo>();
        foreach (var attribute in candidate.SerializableAttributes)
        {
            if (attribute.ConstructorArguments.Length != 1 || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol model)
            {
                continue;
            }

            var modelInfo = CreateModelInfo(context, model, skipElements);
            if (modelInfo is not null)
            {
                models.Add(modelInfo);
            }
        }

        if (models.Count == 0)
        {
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        if (!candidate.Symbol.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ").Append(candidate.Symbol.ContainingNamespace.ToDisplayString()).AppendLine(";");
            source.AppendLine();
        }

        source.Append("partial class ").Append(candidate.Symbol.Name).AppendLine();
        source.AppendLine("{");
        foreach (var model in models)
        {
            EmitTypeInfo(source, model);
            EmitHandler(source, model);
        }
        source.AppendLine("}");

        context.AddSource($"{candidate.Symbol.Name}.TurboXmlSerializer.g.cs", source.ToString());
    }

    private static Dictionary<INamedTypeSymbol, ImmutableArray<string>> GetSkipElements(INamedTypeSymbol context)
    {
        var result = new Dictionary<INamedTypeSymbol, ImmutableArray<string>>(SymbolEqualityComparer.Default);
        foreach (var attribute in context.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != "TurboXml.Serialization.TurboXmlSkipUnknownElementAttribute"
                || attribute.ConstructorArguments.Length != 2
                || attribute.ConstructorArguments[0].Value is not INamedTypeSymbol model
                || attribute.ConstructorArguments[1].Value is not string elementName)
            {
                continue;
            }

            if (result.TryGetValue(model, out var names))
            {
                result[model] = names.Add(elementName);
            }
            else
            {
                result.Add(model, ImmutableArray.Create(elementName));
            }
        }

        return result;
    }

    private static ModelInfo? CreateModelInfo(
        SourceProductionContext context,
        INamedTypeSymbol model,
        Dictionary<INamedTypeSymbol, ImmutableArray<string>> skipElements)
    {
        if (model.IsAbstract || model.Constructors.All(static constructor => constructor.Parameters.Length != 0 || constructor.DeclaredAccessibility != Accessibility.Public))
        {
            context.ReportDiagnostic(Diagnostic.Create(UnsupportedProperty, model.Locations.FirstOrDefault(), model.Name, model.Name, "a public parameterless constructor is required"));
            return null;
        }

        var members = new List<MemberInfo>();
        IPropertySymbol? unknownProperty = null;
        foreach (var property in GetSerializableProperties(model))
        {
            if (property.IsStatic || property.SetMethod is null || property.SetMethod.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (HasAttribute(property, "System.Xml.Serialization.XmlIgnoreAttribute"))
            {
                continue;
            }

            if (HasAttribute(property, "System.Xml.Serialization.XmlAnyElementAttribute"))
            {
                if (property.Type is IArrayTypeSymbol { ElementType: INamedTypeSymbol elementType }
                    && elementType.ToDisplayString() == "System.Xml.XmlElement")
                {
                    unknownProperty = property;
                    continue;
                }

                context.ReportDiagnostic(Diagnostic.Create(UnsupportedProperty, property.Locations.FirstOrDefault(), property.Name, model.Name, "XmlAnyElement must target XmlElement[]"));
                continue;
            }

            var xmlAttribute = GetAttribute(property, "System.Xml.Serialization.XmlAttributeAttribute");
            var xmlElement = GetAttribute(property, "System.Xml.Serialization.XmlElementAttribute");
            if (xmlAttribute is not null && xmlElement is not null)
            {
                context.ReportDiagnostic(Diagnostic.Create(UnsupportedProperty, property.Locations.FirstOrDefault(), property.Name, model.Name, "a property cannot have both XmlAttribute and XmlElement"));
                continue;
            }

            if (HasAttribute(property, "System.Xml.Serialization.XmlArrayAttribute")
                || property.Type is IArrayTypeSymbol
                || IsList(property.Type))
            {
                context.ReportDiagnostic(Diagnostic.Create(UnsupportedProperty, property.Locations.FirstOrDefault(), property.Name, model.Name, "collections require a generated collection model and are not supported yet"));
                continue;
            }

            if (!TryGetScalarKind(property.Type, out var scalarKind))
            {
                context.ReportDiagnostic(Diagnostic.Create(UnsupportedProperty, property.Locations.FirstOrDefault(), property.Name, model.Name, "nested object types are not supported yet"));
                continue;
            }

            var attributeName = xmlAttribute is null ? null : GetXmlName(xmlAttribute, property.Name);
            var elementName = xmlAttribute is not null
                ? null
                : xmlElement is null
                    ? property.Name
                    : GetXmlName(xmlElement, property.Name);
            members.Add(new MemberInfo(property, attributeName, elementName, scalarKind));
        }

        var rootAttribute = GetAttribute(model, "System.Xml.Serialization.XmlRootAttribute");
        var rootName = rootAttribute is null ? model.Name : GetXmlName(rootAttribute, model.Name);
        skipElements.TryGetValue(model, out var skips);
        return new ModelInfo(model, rootName, members, unknownProperty, skips);
    }

    private static void EmitTypeInfo(StringBuilder source, ModelInfo model)
    {
        var typeName = FullyQualified(model.Symbol);
        var identifier = GetIdentifier(model.Symbol);
        source.Append("    public global::TurboXml.Serialization.TurboXmlTypeInfo<").Append(typeName).Append("> ").Append(identifier).AppendLine(" { get; } = new(");
        source.Append("        Deserialize").Append(identifier).AppendLine(",");
        source.Append("        Deserialize").Append(identifier).AppendLine("FromStream,");
        source.Append("        Deserialize").Append(identifier).AppendLine("Array,");
        source.Append("        Deserialize").Append(identifier).AppendLine("ArrayFromStream);");
        source.AppendLine();
        source.Append("    private static ").Append(typeName).Append(" Deserialize").Append(identifier).AppendLine("(string xml)");
        source.AppendLine("    {");
        source.Append("        var handler = new ").Append(identifier).AppendLine("Handler();");
        source.AppendLine("        global::TurboXml.XmlParser.Parse(xml, ref handler);");
        source.AppendLine("        return handler.GetResult();");
        source.AppendLine("    }");
        source.AppendLine();
        source.Append("    private static ").Append(typeName).Append(" Deserialize").Append(identifier).AppendLine("FromStream(global::System.IO.Stream stream)");
        source.AppendLine("    {");
        source.Append("        var handler = new ").Append(identifier).AppendLine("Handler();");
        source.AppendLine("        global::TurboXml.XmlParser.Parse(stream, ref handler);");
        source.AppendLine("        return handler.GetResult();");
        source.AppendLine("    }");
        source.AppendLine();
        source.Append("    private static ").Append(typeName).Append("[] Deserialize").Append(identifier).AppendLine("Array(string xml, string itemElementName)");
        source.AppendLine("    {");
        source.Append("        var handler = new ").Append(identifier).AppendLine("Handler(itemElementName);");
        source.AppendLine("        global::TurboXml.XmlParser.Parse(xml, ref handler);");
        source.AppendLine("        return handler.GetArrayResult();");
        source.AppendLine("    }");
        source.AppendLine();
        source.Append("    private static ").Append(typeName).Append("[] Deserialize").Append(identifier).AppendLine("ArrayFromStream(global::System.IO.Stream stream, string itemElementName)");
        source.AppendLine("    {");
        source.Append("        var handler = new ").Append(identifier).AppendLine("Handler(itemElementName);");
        source.AppendLine("        global::TurboXml.XmlParser.Parse(stream, ref handler);");
        source.AppendLine("        return handler.GetArrayResult();");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void EmitHandler(StringBuilder source, ModelInfo model)
    {
        var typeName = FullyQualified(model.Symbol);
        var identifier = GetIdentifier(model.Symbol);
        source.Append("    private struct ").Append(identifier).AppendLine("Handler : global::TurboXml.IXmlReadHandler");
        source.AppendLine("    {");
        source.Append("        private ").Append(typeName).AppendLine("? _result;");
        source.Append("        private global::System.Collections.Generic.List<").Append(typeName).AppendLine(">? _results;");
        source.AppendLine("        private readonly string? _itemElementName;");
        source.AppendLine("        private int _depth;");
        source.AppendLine("        private int _currentMember;");
        source.AppendLine("        private int _skipDepth;");
        source.AppendLine("        private global::System.Xml.XmlDocument? _unknownDocument;");
        source.AppendLine("        private global::System.Collections.Generic.List<global::System.Xml.XmlElement>? _unknownStack;");
        source.AppendLine("        private global::System.Collections.Generic.List<global::System.Xml.XmlElement>? _unknownElements;");
        source.AppendLine();
        source.Append("        public ").Append(identifier).AppendLine("Handler(string itemElementName)");
        source.AppendLine("        {");
        source.AppendLine("            _result = null;");
        source.AppendLine("            _results = null;");
        source.AppendLine("            _itemElementName = itemElementName;");
        source.AppendLine("            _depth = 0;");
        source.AppendLine("            _currentMember = -1;");
        source.AppendLine("            _skipDepth = 0;");
        source.AppendLine("            _unknownDocument = null;");
        source.AppendLine("            _unknownStack = null;");
        source.AppendLine("            _unknownElements = null;");
        source.AppendLine("        }");
        source.AppendLine();
        source.Append("        public ").Append(identifier).AppendLine("Handler()");
        source.AppendLine("            : this(null!)");
        source.AppendLine("        {");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void OnBeginTag(global::System.ReadOnlySpan<char> name, int line, int column)");
        source.AppendLine("        {");
        source.AppendLine("            _depth++;");
        source.AppendLine("            if (IsCapturingUnknown())");
        source.AppendLine("            {");
        source.AppendLine("                AddUnknownElement(name);");
        source.AppendLine("                return;");
        source.AppendLine("            }");
        source.AppendLine("            if (_skipDepth != 0)");
        source.AppendLine("            {");
        source.AppendLine("                return;");
        source.AppendLine("            }");
        source.AppendLine("            if (_depth == 1)");
        source.AppendLine("            {");
        source.AppendLine("                if (_itemElementName is null)");
        source.AppendLine("                {");
        source.AppendLine("                    if (!name.SequenceEqual(" + Literal(model.RootName) + ".AsSpan())) throw new global::System.Xml.XmlException(\"Unexpected root element.\");");
        source.AppendLine("                    StartResult();");
        source.AppendLine("                }");
        source.AppendLine("                return;");
        source.AppendLine("            }");
        source.AppendLine("            if (_itemElementName is not null && _depth == 2)");
        source.AppendLine("            {");
        source.AppendLine("                if (!name.SequenceEqual(_itemElementName.AsSpan())) return;");
        source.AppendLine("                StartResult();");
        source.AppendLine("                return;");
        source.AppendLine("            }");
        source.AppendLine("            if (!HasCurrentResult() || _depth != ModelDepth() + 1) return;");
        EmitKnownElementDispatch(source, model);
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void OnAttribute(global::System.ReadOnlySpan<char> name, global::System.ReadOnlySpan<char> value, int nameLine, int nameColumn, int valueLine, int valueColumn)");
        source.AppendLine("        {");
        source.AppendLine("            if (IsCapturingUnknown()) { AddUnknownAttribute(name, value); return; }");
        source.AppendLine("            if (_skipDepth != 0 || !HasCurrentResult() || _depth != ModelDepth()) return;");
        EmitAttributeDispatch(source, model);
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void OnText(global::System.ReadOnlySpan<char> text, int line, int column)");
        source.AppendLine("        {");
        source.AppendLine("            if (IsCapturingUnknown()) { AddUnknownText(text); return; }");
        source.AppendLine("            if (_skipDepth == 0 && _currentMember >= 0) SetMember(_currentMember, text);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void OnCData(global::System.ReadOnlySpan<char> cdata, int line, int column)");
        source.AppendLine("        {");
        source.AppendLine("            if (IsCapturingUnknown()) AddUnknownCData(cdata);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void OnComment(global::System.ReadOnlySpan<char> comment, int line, int column)");
        source.AppendLine("        {");
        source.AppendLine("            if (IsCapturingUnknown()) AddUnknownComment(comment);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void OnXmlDeclaration(global::System.ReadOnlySpan<char> version, global::System.ReadOnlySpan<char> encoding, global::System.ReadOnlySpan<char> standalone, int line, int column) { }");
        source.AppendLine("        public void OnError(string message, int line, int column) => throw new global::System.Xml.XmlException(message, null, line + 1, column + 1);");
        source.AppendLine();
        source.AppendLine("        public void OnEndTag(global::System.ReadOnlySpan<char> name, int line, int column) => EndElement();");
        source.AppendLine("        public void OnEndTagEmpty() => EndElement();");
        source.AppendLine();
        source.AppendLine("        public " + typeName + " GetResult() => _result ?? throw new global::System.Xml.XmlException(\"No root element was found.\");");
        source.AppendLine("        public " + typeName + "[] GetArrayResult() => _results?.ToArray() ?? [];");
        source.AppendLine();
        source.AppendLine("        private bool HasCurrentResult() => _result is not null;");
        source.AppendLine("        private int ModelDepth() => _itemElementName is null ? 1 : 2;");
        source.AppendLine("        private bool IsCapturingUnknown() => _unknownStack is not null;");
        source.AppendLine();
        source.AppendLine("        private void StartResult()");
        source.AppendLine("        {");
        source.AppendLine("            _result = new " + typeName + "();");
        source.AppendLine("            _currentMember = -1;");
        source.AppendLine("            _skipDepth = 0;");
        if (model.UnknownProperty is not null)
        {
            source.AppendLine("            _unknownElements = null;");
        }
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private void EndElement()");
        source.AppendLine("        {");
        source.AppendLine("            if (IsCapturingUnknown()) { EndUnknownElement(); _depth--; return; }");
        source.AppendLine("            if (_skipDepth != 0) { if (_depth == _skipDepth) _skipDepth = 0; _depth--; return; }");
        source.AppendLine("            if (_currentMember >= 0 && _depth == ModelDepth() + 1) _currentMember = -1;");
        source.AppendLine("            if (HasCurrentResult() && _depth == ModelDepth()) FinishResult();");
        source.AppendLine("            _depth--;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private void FinishResult()");
        source.AppendLine("        {");
        if (model.UnknownProperty is not null)
        {
            source.AppendLine("            if (_unknownElements is { Count: > 0 }) _result!." + model.UnknownProperty.Name + " = _unknownElements.ToArray();");
        }
        source.AppendLine("            if (_itemElementName is not null)");
        source.AppendLine("            {");
        source.AppendLine("                (_results ??= new global::System.Collections.Generic.List<" + typeName + ">()).Add(_result!);");
        source.AppendLine("                _result = null;");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        EmitSetMember(source, model);
        if (model.UnknownProperty is not null)
        {
            EmitUnknownCapture(source);
        }
        else
        {
            source.AppendLine("        private void CaptureUnknown(global::System.ReadOnlySpan<char> name) { }");
        }
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void EmitKnownElementDispatch(StringBuilder source, ModelInfo model)
    {
        foreach (var skip in model.SkipElements)
        {
            source.Append("            if (name.SequenceEqual(").Append(Literal(skip)).AppendLine(".AsSpan())) { _skipDepth = _depth; return; }");
        }
        for (var index = 0; index < model.Members.Count; index++)
        {
            var member = model.Members[index];
            if (member.ElementName is not null)
            {
                source.Append("            if (name.SequenceEqual(").Append(Literal(member.ElementName)).Append(".AsSpan())) { _currentMember = ").Append(index).AppendLine("; return; }");
            }
        }
        source.AppendLine("            CaptureUnknown(name);");
    }

    private static void EmitAttributeDispatch(StringBuilder source, ModelInfo model)
    {
        for (var index = 0; index < model.Members.Count; index++)
        {
            var member = model.Members[index];
            if (member.AttributeName is not null)
            {
                source.Append("            if (name.SequenceEqual(").Append(Literal(member.AttributeName)).Append(".AsSpan())) { SetMember(").Append(index).AppendLine(", value); return; }");
            }
        }
    }

    private static void EmitSetMember(StringBuilder source, ModelInfo model)
    {
        source.AppendLine("        private void SetMember(int member, global::System.ReadOnlySpan<char> value)");
        source.AppendLine("        {");
        source.AppendLine("            switch (member)");
        source.AppendLine("            {");
        for (var index = 0; index < model.Members.Count; index++)
        {
            var member = model.Members[index];
            source.Append("                case ").Append(index).Append(": _result!.").Append(member.Symbol.Name).Append(" = ").Append(GetParseExpression(member)).AppendLine("; return;");
        }
        source.AppendLine("                default: throw new global::System.InvalidOperationException(\"Unknown generated member.\");");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
    }

    private static void EmitUnknownCapture(StringBuilder source)
    {
        source.AppendLine("        private void CaptureUnknown(global::System.ReadOnlySpan<char> name)");
        source.AppendLine("        {");
        source.AppendLine("            _unknownDocument = new global::System.Xml.XmlDocument();");
        source.AppendLine("            var element = _unknownDocument.CreateElement(name.ToString());");
        source.AppendLine("            _unknownDocument.AppendChild(element);");
        source.AppendLine("            _unknownStack = new global::System.Collections.Generic.List<global::System.Xml.XmlElement> { element };");
        source.AppendLine("        }");
        source.AppendLine("        private void AddUnknownElement(global::System.ReadOnlySpan<char> name)");
        source.AppendLine("        {");
        source.AppendLine("            var element = _unknownDocument!.CreateElement(name.ToString());");
        source.AppendLine("            _unknownStack![_unknownStack.Count - 1].AppendChild(element);");
        source.AppendLine("            _unknownStack.Add(element);");
        source.AppendLine("        }");
        source.AppendLine("        private void AddUnknownAttribute(global::System.ReadOnlySpan<char> name, global::System.ReadOnlySpan<char> value) => _unknownStack![_unknownStack.Count - 1].SetAttribute(name.ToString(), value.ToString());");
        source.AppendLine("        private void AddUnknownText(global::System.ReadOnlySpan<char> value) => _unknownStack![_unknownStack.Count - 1].AppendChild(_unknownDocument!.CreateTextNode(value.ToString()));");
        source.AppendLine("        private void AddUnknownCData(global::System.ReadOnlySpan<char> value) => _unknownStack![_unknownStack.Count - 1].AppendChild(_unknownDocument!.CreateCDataSection(value.ToString()));");
        source.AppendLine("        private void AddUnknownComment(global::System.ReadOnlySpan<char> value) => _unknownStack![_unknownStack.Count - 1].AppendChild(_unknownDocument!.CreateComment(value.ToString()));");
        source.AppendLine("        private void EndUnknownElement()");
        source.AppendLine("        {");
        source.AppendLine("            var index = _unknownStack!.Count - 1;");
        source.AppendLine("            var element = _unknownStack[index];");
        source.AppendLine("            _unknownStack.RemoveAt(index);");
        source.AppendLine("            if (_unknownStack.Count != 0) return;");
        source.AppendLine("            (_unknownElements ??= new global::System.Collections.Generic.List<global::System.Xml.XmlElement>()).Add(element);");
        source.AppendLine("            _unknownDocument = null;");
        source.AppendLine("            _unknownStack = null;");
        source.AppendLine("        }");
        source.AppendLine();
    }

    private static string GetParseExpression(MemberInfo member)
    {
        var targetType = FullyQualified(GetNonNullableType(member.Symbol.Type));
        return member.Kind switch
        {
            ScalarKind.String => "value.ToString()",
            ScalarKind.Boolean => "global::System.Xml.XmlConvert.ToBoolean(value.ToString())",
            ScalarKind.Int32 => "int.Parse(value, global::System.Globalization.CultureInfo.InvariantCulture)",
            ScalarKind.Int64 => "long.Parse(value, global::System.Globalization.CultureInfo.InvariantCulture)",
            ScalarKind.Double => "double.Parse(value, global::System.Globalization.CultureInfo.InvariantCulture)",
            ScalarKind.Decimal => "decimal.Parse(value, global::System.Globalization.CultureInfo.InvariantCulture)",
            ScalarKind.Guid => "global::System.Guid.Parse(value)",
            ScalarKind.DateTime => "global::System.Xml.XmlConvert.ToDateTime(value.ToString(), global::System.Xml.XmlDateTimeSerializationMode.RoundtripKind)",
            ScalarKind.DateTimeOffset => "global::System.Xml.XmlConvert.ToDateTimeOffset(value.ToString())",
            ScalarKind.Enum => "global::System.Enum.TryParse<" + targetType + ">(value, false, out var parsed) ? parsed : throw new global::System.FormatException(\"Invalid enum value.\")",
            _ => throw new InvalidOperationException()
        };
    }

    private static bool TryGetScalarKind(ITypeSymbol type, out ScalarKind kind)
    {
        var nullable = GetNonNullableType(type);

        if (nullable.TypeKind == TypeKind.Enum)
        {
            kind = ScalarKind.Enum;
            return true;
        }

        kind = nullable.SpecialType switch
        {
            SpecialType.System_String => ScalarKind.String,
            SpecialType.System_Boolean => ScalarKind.Boolean,
            SpecialType.System_Int32 => ScalarKind.Int32,
            SpecialType.System_Int64 => ScalarKind.Int64,
            SpecialType.System_Double => ScalarKind.Double,
            SpecialType.System_Decimal => ScalarKind.Decimal,
            _ when nullable.ToDisplayString() == "System.Guid" => ScalarKind.Guid,
            _ when nullable.ToDisplayString() == "System.DateTime" => ScalarKind.DateTime,
            _ when nullable.ToDisplayString() == "System.DateTimeOffset" => ScalarKind.DateTimeOffset,
            _ => ScalarKind.None
        };
        return kind != ScalarKind.None;
    }

    private static ITypeSymbol GetNonNullableType(ITypeSymbol type)
    {
        return type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
            && type is INamedTypeSymbol namedNullable
            ? namedNullable.TypeArguments[0]
            : type;
    }

    private static bool IsList(ITypeSymbol type) => type.AllInterfaces.Any(static interfaceType => interfaceType.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IList<T>");

    private static IEnumerable<IPropertySymbol> GetSerializableProperties(INamedTypeSymbol model)
    {
        for (var current = model; current is not null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
        {
            foreach (var property in current.GetMembers().OfType<IPropertySymbol>())
            {
                yield return property;
            }
        }
    }

    private static bool HasAttribute(ISymbol symbol, string name) => GetAttribute(symbol, name) is not null;

    private static AttributeData? GetAttribute(ISymbol symbol, string name) => symbol.GetAttributes().FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == name);

    private static string GetXmlName(AttributeData attribute, string fallback)
    {
        if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string name && name.Length > 0)
        {
            return name;
        }

        foreach (var pair in attribute.NamedArguments)
        {
            if (pair.Key == "ElementName" && pair.Value.Value is string elementName && elementName.Length > 0)
            {
                return elementName;
            }

            if (pair.Key == "AttributeName" && pair.Value.Value is string attributeName && attributeName.Length > 0)
            {
                return attributeName;
            }
        }

        return fallback;
    }

    private static string FullyQualified(ITypeSymbol symbol) => symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string GetIdentifier(INamedTypeSymbol symbol) => symbol.Name + "TypeInfo";

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, true);

    private sealed class ContextCandidate
    {
        public ContextCandidate(INamedTypeSymbol symbol, bool isPartial, ImmutableArray<AttributeData> serializableAttributes)
        {
            Symbol = symbol;
            IsPartial = isPartial;
            SerializableAttributes = serializableAttributes;
        }

        public INamedTypeSymbol Symbol { get; }

        public bool IsPartial { get; }

        public ImmutableArray<AttributeData> SerializableAttributes { get; }
    }

    private sealed class ModelInfo
    {
        public ModelInfo(INamedTypeSymbol symbol, string rootName, List<MemberInfo> members, IPropertySymbol? unknownProperty, ImmutableArray<string> skipElements)
        {
            Symbol = symbol;
            RootName = rootName;
            Members = members;
            UnknownProperty = unknownProperty;
            SkipElements = skipElements;
        }

        public INamedTypeSymbol Symbol { get; }

        public string RootName { get; }

        public List<MemberInfo> Members { get; }

        public IPropertySymbol? UnknownProperty { get; }

        public ImmutableArray<string> SkipElements { get; }
    }

    private sealed class MemberInfo
    {
        public MemberInfo(IPropertySymbol symbol, string? attributeName, string? elementName, ScalarKind kind)
        {
            Symbol = symbol;
            AttributeName = attributeName;
            ElementName = elementName;
            Kind = kind;
        }

        public IPropertySymbol Symbol { get; }

        public string? AttributeName { get; }

        public string? ElementName { get; }

        public ScalarKind Kind { get; }
    }

    private enum ScalarKind
    {
        None,
        String,
        Boolean,
        Int32,
        Int64,
        Double,
        Decimal,
        Guid,
        DateTime,
        DateTimeOffset,
        Enum
    }
}
